
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__energy_adaptor_hpp__ADAPTOR_MARSHAL_H
#define __dbusxx__energy_adaptor_hpp__ADAPTOR_MARSHAL_H

#include <dbus-c++-1/dbus-c++/dbus.h>
#include <cassert>

namespace org {
namespace freedesktop {
namespace keti {
namespace bmc {

class energy_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

    energy_adaptor()
    : ::DBus::InterfaceAdaptor("org.freedesktop.keti.bmc.energy")
    {
        register_method(energy_adaptor, emm_ibmc, _emm_ibmc_stub);
        register_method(energy_adaptor, emm_policy, _emm_policy_stub);
        register_method(energy_adaptor, emm_feedback, _emm_feedback_stub);
        register_method(energy_adaptor, emm_monitor, _emm_monitor_stub);
        register_method(energy_adaptor, emm_ssp, _emm_ssp_stub);
    }

    ::DBus::IntrospectedInterface *introspect() const 
    {
        static ::DBus::IntrospectedArgument emm_ibmc_args[] = 
        {
            { "result", "i", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument emm_policy_args[] = 
        {
            { "result", "i", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument emm_feedback_args[] = 
        {
            { "result", "i", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument emm_monitor_args[] = 
        {
            { "result", "i", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument emm_ssp_args[] = 
        {
            { "result", "i", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod energy_adaptor_methods[] = 
        {
            { "emm_ibmc", emm_ibmc_args },
            { "emm_policy", emm_policy_args },
            { "emm_feedback", emm_feedback_args },
            { "emm_monitor", emm_monitor_args },
            { "emm_ssp", emm_ssp_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod energy_adaptor_signals[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty energy_adaptor_properties[] = 
        {
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface energy_adaptor_interface = 
        {
            "org.freedesktop.keti.bmc.energy",
            energy_adaptor_methods,
            energy_adaptor_signals,
            energy_adaptor_properties
        };
        return &energy_adaptor_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual int32_t emm_ibmc() = 0;
    virtual int32_t emm_policy() = 0;
    virtual int32_t emm_feedback() = 0;
    virtual int32_t emm_monitor() = 0;
    virtual int32_t emm_ssp() = 0;

public:

    /* signal emitters for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _emm_ibmc_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        int32_t argout1 = emm_ibmc();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _emm_policy_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        int32_t argout1 = emm_policy();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _emm_feedback_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        int32_t argout1 = emm_feedback();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _emm_monitor_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        int32_t argout1 = emm_monitor();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _emm_ssp_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        int32_t argout1 = emm_ssp();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
};

} } } } 
#endif //__dbusxx__energy_adaptor_hpp__ADAPTOR_MARSHAL_H
